/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classprojectoop;

import javax.swing.JPanel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author arets
 */
public class userProfileForm extends javax.swing.JFrame {
DatabaseTableCreater dbc = new DatabaseTableCreater();
    /**
     * Creates new form New_User_Form
     */
    public userProfileForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        emailTf = new javax.swing.JTextField();
        userNameTF = new javax.swing.JTextField();
        password2Lbl = new javax.swing.JTextField();
        exitBtn = new javax.swing.JButton();
        mpBtn = new javax.swing.JButton();
        returnBtn = new javax.swing.JButton();
        userNameLbl = new javax.swing.JTextField();
        userLastNameLbl = new javax.swing.JTextField();
        confirmLbl = new javax.swing.JTextField();
        userLastNameTF = new javax.swing.JTextField();
        phoneNoTF = new javax.swing.JTextField();
        passwordTF = new javax.swing.JTextField();
        password2TF = new javax.swing.JTextField();
        passwordLbl = new javax.swing.JTextField();
        phoneNoLbl = new javax.swing.JTextField();
        emailLbl = new javax.swing.JTextField();
        check18 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(720, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emailTf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        jPanel1.add(emailTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 370, 30));

        userNameTF.setToolTipText("");
        userNameTF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        jPanel1.add(userNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 370, 30));

        password2Lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        password2Lbl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        password2Lbl.setText("Password again");
        jPanel1.add(password2Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 120, 30));

        exitBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        jPanel1.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 450, 80, 40));

        mpBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mpBtn.setText("Main Page");
        mpBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        mpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpBtnActionPerformed(evt);
            }
        });
        jPanel1.add(mpBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, 110, 40));
        mpBtn.getAccessibleContext().setAccessibleDescription("");

        returnBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        returnBtn.setText("Return");
        returnBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        returnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnActionPerformed(evt);
            }
        });
        jPanel1.add(returnBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, 90, 40));

        userNameLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userNameLbl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userNameLbl.setText("First Name ");
        userNameLbl.setActionCommand("<Not Set>");
        userNameLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        userNameLbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameLblActionPerformed(evt);
            }
        });
        jPanel1.add(userNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 120, 30));

        userLastNameLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userLastNameLbl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userLastNameLbl.setText("Last name ");
        jPanel1.add(userLastNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 120, 30));

        confirmLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        confirmLbl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        confirmLbl.setText("I confirm +18");
        jPanel1.add(confirmLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 120, 30));

        userLastNameTF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        jPanel1.add(userLastNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 370, 30));

        phoneNoTF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        jPanel1.add(phoneNoTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 370, 30));

        passwordTF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        jPanel1.add(passwordTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 370, 30));

        password2TF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        jPanel1.add(password2TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 370, 30));

        passwordLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        passwordLbl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordLbl.setText("Password");
        jPanel1.add(passwordLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 120, 30));

        phoneNoLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        phoneNoLbl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        phoneNoLbl.setText("Phone ");
        phoneNoLbl.setToolTipText("");
        phoneNoLbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNoLblActionPerformed(evt);
            }
        });
        jPanel1.add(phoneNoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 120, 30));

        emailLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        emailLbl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emailLbl.setText("Email");
        jPanel1.add(emailLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 120, 30));

        check18.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        jPanel1.add(check18, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 50, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 102));
        jLabel4.setText("Account User Profile Form");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 360, 30));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_chat/User_profile_Front_Back_1.png"))); // NOI18N
        jLabel6.setToolTipText("");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_chat/User_profile_Front_Back_1.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 330, -1));

        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_chat/Form_BackGround.png3.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 720, 480));
        jLabel1.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 720, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userNameLblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameLblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameLblActionPerformed

    private void phoneNoLblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNoLblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNoLblActionPerformed

    private void mpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpBtnActionPerformed
        // TODO add your handling code here:
        Front_main_Page fmp = new Front_main_Page();
        fmp.setVisible(true);
        this.setVisible(false);
        
        
        
    }//GEN-LAST:event_mpBtnActionPerformed

    private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed
        // TODO add your handling code here:
    
        
        
        
    }//GEN-LAST:event_returnBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userProfileForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userProfileForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userProfileForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userProfileForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
            new mesagesPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox check18;
    private javax.swing.JTextField confirmLbl;
    private javax.swing.JTextField emailLbl;
    private javax.swing.JTextField emailTf;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mpBtn;
    private javax.swing.JTextField password2Lbl;
    private javax.swing.JTextField password2TF;
    private javax.swing.JTextField passwordLbl;
    private javax.swing.JTextField passwordTF;
    private javax.swing.JTextField phoneNoLbl;
    private javax.swing.JTextField phoneNoTF;
    private javax.swing.JButton returnBtn;
    private javax.swing.JTextField userLastNameLbl;
    private javax.swing.JTextField userLastNameTF;
    private javax.swing.JTextField userNameLbl;
    private javax.swing.JTextField userNameTF;
    // End of variables declaration//GEN-END:variables
}
