/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classprojectoop;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Administrator
 */
public class frontMainPage extends javax.swing.JFrame {

    /**
     * Creates new frontMainPage
     */
    public frontMainPage() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fmpPanel = new javax.swing.JPanel();
        passwordTF = new javax.swing.JPasswordField();
        showPassword = new javax.swing.JCheckBox();
        nameTF = new javax.swing.JTextField();
        mainPageText1Lbl = new javax.swing.JLabel();
        passwordLbl = new javax.swing.JLabel();
        userLbl = new javax.swing.JLabel();
        logoMainPageLbl = new javax.swing.JLabel();
        mainPageText2Lbl = new javax.swing.JLabel();
        mainPageText4Lbl = new javax.swing.JLabel();
        mainPageText3Lbl = new javax.swing.JLabel();
        exitBtn = new javax.swing.JButton();
        newUserBtn = new javax.swing.JButton();
        loginBtn = new javax.swing.JButton();
        ImageMainPageLbl = new javax.swing.JLabel();
        backgrounPageImageLbl = new javax.swing.JLabel();
        mainPageImageLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(720, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fmpPanel.setMinimumSize(new java.awt.Dimension(780, 500));
        fmpPanel.setPreferredSize(new java.awt.Dimension(780, 500));
        fmpPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passwordTF.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        passwordTF.setForeground(new java.awt.Color(153, 153, 153));
        fmpPanel.add(passwordTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 200, 30));

        showPassword.setBackground(new java.awt.Color(255, 102, 0));
        showPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        showPassword.setForeground(new java.awt.Color(255, 255, 255));
        showPassword.setText("Show Password ");
        showPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordActionPerformed(evt);
            }
        });
        fmpPanel.add(showPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, -1, 20));

        nameTF.setColumns(2);
        nameTF.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nameTF.setForeground(new java.awt.Color(153, 153, 153));
        nameTF.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nameTF.setToolTipText("");
        nameTF.setActionCommand("<Not Set>");
        nameTF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nameTF.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        nameTF.setName(""); // NOI18N
        nameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTFActionPerformed(evt);
            }
        });
        fmpPanel.add(nameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 200, 30));

        mainPageText1Lbl.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        mainPageText1Lbl.setForeground(new java.awt.Color(255, 255, 255));
        mainPageText1Lbl.setText("Save your snip of memories");
        fmpPanel.add(mainPageText1Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 360, 40));

        passwordLbl.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        passwordLbl.setForeground(new java.awt.Color(255, 255, 255));
        passwordLbl.setText("Password");
        fmpPanel.add(passwordLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 110, 30));

        userLbl.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        userLbl.setForeground(new java.awt.Color(255, 255, 255));
        userLbl.setText("User name");
        fmpPanel.add(userLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 120, 30));

        logoMainPageLbl.setBackground(new java.awt.Color(255, 255, 255));
        logoMainPageLbl.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        logoMainPageLbl.setForeground(new java.awt.Color(255, 255, 255));
        logoMainPageLbl.setText("HERMES");
        fmpPanel.add(logoMainPageLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, 280, 50));

        mainPageText2Lbl.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        mainPageText2Lbl.setForeground(new java.awt.Color(255, 255, 255));
        mainPageText2Lbl.setText("Share your impressions");
        fmpPanel.add(mainPageText2Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 250, 60));

        mainPageText4Lbl.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        mainPageText4Lbl.setForeground(new java.awt.Color(255, 255, 255));
        mainPageText4Lbl.setText("Stay with HERMES");
        fmpPanel.add(mainPageText4Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 220, 30));

        mainPageText3Lbl.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        mainPageText3Lbl.setForeground(new java.awt.Color(255, 255, 255));
        mainPageText3Lbl.setText("Stay Log on");
        fmpPanel.add(mainPageText3Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 160, 30));

        exitBtn.setBackground(new java.awt.Color(51, 102, 255));
        exitBtn.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn.setText("Exit");
        exitBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        fmpPanel.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 120, 50));

        newUserBtn.setBackground(new java.awt.Color(0, 204, 51));
        newUserBtn.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        newUserBtn.setForeground(new java.awt.Color(255, 255, 255));
        newUserBtn.setText(" Create New Account ");
        newUserBtn.setActionCommand(" Log In");
        newUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newUserBtnActionPerformed(evt);
            }
        });
        fmpPanel.add(newUserBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 270, 50));

        loginBtn.setBackground(new java.awt.Color(51, 102, 255));
        loginBtn.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Log In");
        loginBtn.setActionCommand(" Log In");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        fmpPanel.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 140, 40));

        ImageMainPageLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_chat/Logo_chat_Main_page.png"))); // NOI18N
        ImageMainPageLbl.setToolTipText("");
        fmpPanel.add(ImageMainPageLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 320, 270));

        backgrounPageImageLbl.setBackground(new java.awt.Color(255, 255, 255));
        backgrounPageImageLbl.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        backgrounPageImageLbl.setForeground(new java.awt.Color(255, 255, 255));
        backgrounPageImageLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_chat/Image_Main_page.gif"))); // NOI18N
        backgrounPageImageLbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        fmpPanel.add(backgrounPageImageLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 700, 300));

        mainPageImageLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_chat/Snip_for_main_Page01.jpg"))); // NOI18N
        mainPageImageLbl.setMaximumSize(new java.awt.Dimension(720, 500));
        mainPageImageLbl.setMinimumSize(new java.awt.Dimension(720, 500));
        fmpPanel.add(mainPageImageLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 500));
        mainPageImageLbl.getAccessibleContext().setAccessibleName("");

        getContentPane().add(fmpPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        if (nameTF.getText().equals("")){
        JOptionPane.showMessageDialog(null,"Please fill out User name ");  /// Pop-up message at 
        } 
        else if (passwordTF.getText().equals("")){
        JOptionPane.showMessageDialog(null,"Please fill out Password");  /// Pop-up Message at need to fiil out teh password
        }
        else if (nameTF.getText().contains("Andrei")&& passwordTF.getText().contains("12345")){   /// User name and Login Cridentias 
        JOptionPane.showMessageDialog(null,"Login User");
         System.out.println("User Login");
           
           messageForm mf = new messageForm (); 
           mf.setVisible(true);
           this.setVisible(false);
           System.out.println("next Page");
        }
        else {
           JOptionPane.showMessageDialog(null ,"Wrong User Name or Password","Message" , JOptionPane.ERROR_MESSAGE);   
        }
      
    }//GEN-LAST:event_loginBtnActionPerformed

    private void showPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordActionPerformed
        // TODO add your handling code here:
        if (showPassword.isSelected()){
        passwordTF.setEchoChar((char)0);
        }
        else{
            passwordTF.setEchoChar(('*'));
        }
            
    }//GEN-LAST:event_showPasswordActionPerformed

    private void nameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTFActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_nameTFActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void newUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newUserBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newUserBtnActionPerformed
       
          
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frontMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frontMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frontMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frontMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frontMainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImageMainPageLbl;
    private javax.swing.JLabel backgrounPageImageLbl;
    private javax.swing.JButton exitBtn;
    private javax.swing.JPanel fmpPanel;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel logoMainPageLbl;
    private javax.swing.JLabel mainPageImageLbl;
    private javax.swing.JLabel mainPageText1Lbl;
    private javax.swing.JLabel mainPageText2Lbl;
    private javax.swing.JLabel mainPageText3Lbl;
    private javax.swing.JLabel mainPageText4Lbl;
    private javax.swing.JTextField nameTF;
    private javax.swing.JButton newUserBtn;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JPasswordField passwordTF;
    private javax.swing.JCheckBox showPassword;
    private javax.swing.JLabel userLbl;
    // End of variables declaration//GEN-END:variables
}
