/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classprojectoop;

/**
 *
 * @author arets
 */
public class frontPage extends javax.swing.JFrame {

    /**
     * Creates new form frontPage
     */
    public frontPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jButton1 = new javax.swing.JButton();
        helpBtn = new javax.swing.JButton();
        newAccountBtn = new javax.swing.JButton();
        nameTF = new javax.swing.JTextField();
        passwordTF = new javax.swing.JTextField();
        emailTF = new javax.swing.JTextField();
        newAccountLbl = new javax.swing.JLabel();
        passroedLbl = new javax.swing.JLabel();
        topTextLbl = new javax.swing.JLabel();
        mainPageImageLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setPreferredSize(new java.awt.Dimension(720, 500));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLayeredPane1.setMinimumSize(new java.awt.Dimension(720, 500));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Sign up");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jLayeredPane1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 300, 50));

        helpBtn.setBackground(new java.awt.Color(255, 153, 0));
        helpBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        helpBtn.setText("HELP");
        helpBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jLayeredPane1.add(helpBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 110, 40));

        newAccountBtn.setBackground(new java.awt.Color(255, 153, 0));
        newAccountBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newAccountBtn.setText("An New Account");
        newAccountBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        newAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAccountBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(newAccountBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 150, 40));

        nameTF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nameTF.setText("  Your name ");
        nameTF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        jLayeredPane1.add(nameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 550, 40));

        passwordTF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        passwordTF.setText("  Password");
        passwordTF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        jLayeredPane1.add(passwordTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 550, 40));

        emailTF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        emailTF.setText("  Email ");
        emailTF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        jLayeredPane1.add(emailTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 550, 40));

        newAccountLbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        newAccountLbl.setForeground(new java.awt.Color(255, 255, 255));
        newAccountLbl.setText("for new Account ");
        jLayeredPane1.add(newAccountLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 110, 40));

        passroedLbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        passroedLbl.setForeground(new java.awt.Color(255, 255, 255));
        passroedLbl.setText("forgot password");
        jLayeredPane1.add(passroedLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 110, 40));

        topTextLbl.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        topTextLbl.setForeground(new java.awt.Color(255, 255, 255));
        topTextLbl.setText("Log on \"Friendly Chat \"");
        jLayeredPane1.add(topTextLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 500, 50));

        mainPageImageLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_chat/Background_page_Front_Page.png"))); // NOI18N
        mainPageImageLbl.setAlignmentY(0.0F);
        mainPageImageLbl.setPreferredSize(new java.awt.Dimension(720, 500));
        jLayeredPane1.add(mainPageImageLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 520));
        mainPageImageLbl.getAccessibleContext().setAccessibleDescription("");

        jPanel1.add(jLayeredPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 500));
        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAccountBtnActionPerformed
        userProfileForm upf = new userProfileForm();
        upf.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_newAccountBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frontPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailTF;
    private javax.swing.JButton helpBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mainPageImageLbl;
    private javax.swing.JTextField nameTF;
    private javax.swing.JButton newAccountBtn;
    private javax.swing.JLabel newAccountLbl;
    private javax.swing.JLabel passroedLbl;
    private javax.swing.JTextField passwordTF;
    private javax.swing.JLabel topTextLbl;
    // End of variables declaration//GEN-END:variables
}
