/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classprojectoop;



/**
 *
 * @author arets
 */
public class messageForm extends javax.swing.JFrame {
    //  a list of users    
    DatabaseTableCreater dbc = new DatabaseTableCreater();
    
    /**
     * Creates new form messageForm
     */
    public messageForm() {
        initComponents();
         // Populate the JComboBox with the list of users
       
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        topTextLbl = new javax.swing.JLabel();
        exitBtn = new javax.swing.JButton();
        mainPageBtn = new javax.swing.JButton();
        nextPageBtn = new javax.swing.JButton();
        sendMessageBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        comboBoxUsers = new javax.swing.JComboBox<>();
        scrollPanelUser1 = new javax.swing.JScrollPane();
        message1TA = new javax.swing.JTextArea();
        userLbl1 = new javax.swing.JLabel();
        backgroundMessage1Lbl = new javax.swing.JLabel();
        userImage2Lbl = new javax.swing.JLabel();
        scrollPanelUser2 = new javax.swing.JScrollPane();
        message2TA = new javax.swing.JTextArea();
        userlbl2 = new java.awt.Label();
        backgroundMessage2Lbl = new javax.swing.JLabel();
        userImage1Lbl = new javax.swing.JLabel();
        subMainPageImageLbl = new javax.swing.JLabel();
        searchBarTF = new javax.swing.JTextField();
        mainPageImageLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topTextLbl.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        topTextLbl.setForeground(new java.awt.Color(255, 153, 0));
        topTextLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        topTextLbl.setText("Chat Console ");
        topTextLbl.setToolTipText("");
        jPanel1.add(topTextLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 40));

        exitBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 3, true));
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, 130, 40));

        mainPageBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mainPageBtn.setText("Main Page");
        mainPageBtn.setActionCommand("Back");
        mainPageBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 3, true));
        mainPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainPageBtnActionPerformed(evt);
            }
        });
        jPanel1.add(mainPageBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 120, 40));

        nextPageBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nextPageBtn.setText("Next page");
        nextPageBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 3, true));
        jPanel1.add(nextPageBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, 120, 40));

        sendMessageBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sendMessageBtn.setText("Send");
        sendMessageBtn.setToolTipText("");
        sendMessageBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 3, true));
        sendMessageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendMessageBtnActionPerformed(evt);
            }
        });
        jPanel1.add(sendMessageBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 90, 40));

        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_chat/Search_Image.png"))); // NOI18N
        searchBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 2, true));
        jPanel1.add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 40, 30));

        comboBoxUsers.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        comboBoxUsers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Item 2", "Item 3", "Item 4" }));
        comboBoxUsers.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 3, true));
        comboBoxUsers.setName(""); // NOI18N
        comboBoxUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxUsersActionPerformed(evt);
            }
        });
        jPanel1.add(comboBoxUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 190, 30));

        message1TA.setBackground(new java.awt.Color(51, 255, 0));
        message1TA.setColumns(20);
        message1TA.setRows(5);
        scrollPanelUser1.setViewportView(message1TA);

        jPanel1.add(scrollPanelUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 240, 110));

        userLbl1.setBackground(new java.awt.Color(255, 255, 255));
        userLbl1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        userLbl1.setText("user1");
        userLbl1.setToolTipText("");
        jPanel1.add(userLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 100, 20));

        backgroundMessage1Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backgroundMessage1Lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_chat/chat bacground .png12323.png"))); // NOI18N
        backgroundMessage1Lbl.setToolTipText("");
        backgroundMessage1Lbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        jPanel1.add(backgroundMessage1Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 400, 130));

        userImage2Lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_chat/user_Image_1.png"))); // NOI18N
        userImage2Lbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        jPanel1.add(userImage2Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 50, 60));

        message2TA.setBackground(new java.awt.Color(0, 153, 204));
        message2TA.setColumns(20);
        message2TA.setRows(5);
        scrollPanelUser2.setViewportView(message2TA);

        jPanel1.add(scrollPanelUser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 240, 110));

        userlbl2.setAlignment(java.awt.Label.CENTER);
        userlbl2.setBackground(new java.awt.Color(255, 153, 51));
        userlbl2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        userlbl2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        userlbl2.setName(""); // NOI18N
        userlbl2.setText("User2");
        userlbl2.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                userlbl2InputMethodTextChanged(evt);
            }
        });
        jPanel1.add(userlbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 100, 30));

        backgroundMessage2Lbl.setForeground(new java.awt.Color(255, 255, 255));
        backgroundMessage2Lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_chat/new 123.png"))); // NOI18N
        backgroundMessage2Lbl.setToolTipText("");
        backgroundMessage2Lbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        jPanel1.add(backgroundMessage2Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 400, 130));

        userImage1Lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_chat/user_Image_2.png"))); // NOI18N
        userImage1Lbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        jPanel1.add(userImage1Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 50, 60));

        subMainPageImageLbl.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        subMainPageImageLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_chat/Chat_Cansole_p1.gif"))); // NOI18N
        subMainPageImageLbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.add(subMainPageImageLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 720, 400));

        searchBarTF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchBarTF.setText("  Search ");
        searchBarTF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 3, true));
        searchBarTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBarTFActionPerformed(evt);
            }
        });
        jPanel1.add(searchBarTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 210, 30));

        mainPageImageLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_chat/Bacground_ Chat_Console.jpg"))); // NOI18N
        jPanel1.add(mainPageImageLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainPageBtnActionPerformed
    frontPage fp = new frontPage();
        fp.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_mainPageBtnActionPerformed

    private void sendMessageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendMessageBtnActionPerformed
      // TODO add your handling code here:
      //  String user = userTF.getText();
       // String password = passwordTF.getText();
        //String email = emailTF.getText();
      // dbc.insertUser(user,password,email);
       String message = message1TA.getText();
       dbc.sendMessage(message);
       System.out.println("message Created"); 
    }//GEN-LAST:event_sendMessageBtnActionPerformed

    private void comboBoxUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxUsersActionPerformed
         // TODO add your handling code here:
        // Get the selected User from the JComboBox
       
    }//GEN-LAST:event_comboBoxUsersActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
     System.exit(WIDTH);
        // TODO add your handling code here:
    }//GEN-LAST:event_exitBtnActionPerformed

    private void searchBarTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBarTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBarTFActionPerformed

    private void userlbl2InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_userlbl2InputMethodTextChanged
        // TODO add your handling code here:
        String user = userlbl2.getText();
    }//GEN-LAST:event_userlbl2InputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(messageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(messageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(messageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(messageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new messageForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundMessage1Lbl;
    private javax.swing.JLabel backgroundMessage2Lbl;
    private javax.swing.JComboBox<String> comboBoxUsers;
    private javax.swing.JButton exitBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mainPageBtn;
    private javax.swing.JLabel mainPageImageLbl;
    private javax.swing.JTextArea message1TA;
    private javax.swing.JTextArea message2TA;
    private javax.swing.JButton nextPageBtn;
    private javax.swing.JScrollPane scrollPanelUser1;
    private javax.swing.JScrollPane scrollPanelUser2;
    private javax.swing.JTextField searchBarTF;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton sendMessageBtn;
    private javax.swing.JLabel subMainPageImageLbl;
    private javax.swing.JLabel topTextLbl;
    private javax.swing.JLabel userImage1Lbl;
    private javax.swing.JLabel userImage2Lbl;
    private javax.swing.JLabel userLbl1;
    private java.awt.Label userlbl2;
    // End of variables declaration//GEN-END:variables

}

