/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classprojectoop;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author arets
 */
public class userProfileForm extends javax.swing.JFrame {
    DatabaseTableCreater dbc = new DatabaseTableCreater();
   // frontPage fp = new frontPage ();
  
    
    /**
     * Creates new form userProfileForm
     */
    public userProfileForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        emailTF = new javax.swing.JTextField();
        userTF = new javax.swing.JTextField();
        exitBtn = new javax.swing.JButton();
        mainPageBtn = new javax.swing.JButton();
        mainPageText1 = new javax.swing.JLabel();
        CreateNewUserBtn = new javax.swing.JButton();
        returnBtn = new javax.swing.JButton();
        userNameLbl = new java.awt.Label();
        label4 = new java.awt.Label();
        passwordLbl = new java.awt.Label();
        passwordTF = new javax.swing.JTextField();
        ageConfirm = new java.awt.Label();
        ageConfirmCB = new javax.swing.JCheckBox();
        mainPageText = new javax.swing.JLabel();
        mainPageRightImage = new javax.swing.JLabel();
        mainPageLeftImage = new javax.swing.JLabel();
        MainPageBackgroundImage = new javax.swing.JLabel();
        mainPageText2 = new javax.swing.JLabel();

        jPanel2.setLayout(new java.awt.GridBagLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(730, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(730, 520));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        emailTF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 28;
        gridBagConstraints.ipadx = 306;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 20, 0, 0);
        jPanel1.add(emailTF, gridBagConstraints);

        userTF.setToolTipText("");
        userTF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        userTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 28;
        gridBagConstraints.ipadx = 306;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 20, 0, 0);
        jPanel1.add(userTF, gridBagConstraints);

        exitBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 30;
        gridBagConstraints.gridheight = 8;
        gridBagConstraints.ipadx = 52;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 10, 0, 0);
        jPanel1.add(exitBtn, gridBagConstraints);

        mainPageBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mainPageBtn.setText("Main Page");
        mainPageBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        mainPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainPageBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 8;
        gridBagConstraints.ipadx = 35;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 60, 0, 0);
        jPanel1.add(mainPageBtn, gridBagConstraints);
        mainPageBtn.getAccessibleContext().setAccessibleDescription("");

        mainPageText1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        mainPageText1.setForeground(new java.awt.Color(102, 0, 102));
        mainPageText1.setText("Please Add your Details");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 61;
        gridBagConstraints.ipady = -10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 0, 0);
        jPanel1.add(mainPageText1, gridBagConstraints);

        CreateNewUserBtn.setBackground(new java.awt.Color(0, 102, 255));
        CreateNewUserBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CreateNewUserBtn.setForeground(new java.awt.Color(255, 255, 255));
        CreateNewUserBtn.setText("Create");
        CreateNewUserBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        CreateNewUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateNewUserBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.ipadx = 61;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 120, 0, 0);
        jPanel1.add(CreateNewUserBtn, gridBagConstraints);

        returnBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        returnBtn.setText("Return");
        returnBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        returnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 8;
        gridBagConstraints.ipadx = 42;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 10, 0, 0);
        jPanel1.add(returnBtn, gridBagConstraints);

        userNameLbl.setAlignment(java.awt.Label.CENTER);
        userNameLbl.setBackground(new java.awt.Color(255, 255, 255));
        userNameLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        userNameLbl.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        userNameLbl.setName(""); // NOI18N
        userNameLbl.setText("First Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 41;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 120, 0, 0);
        jPanel1.add(userNameLbl, gridBagConstraints);

        label4.setAlignment(java.awt.Label.CENTER);
        label4.setBackground(new java.awt.Color(255, 255, 255));
        label4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        label4.setText("Email");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 79;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 120, 0, 0);
        jPanel1.add(label4, gridBagConstraints);

        passwordLbl.setAlignment(java.awt.Label.CENTER);
        passwordLbl.setBackground(new java.awt.Color(255, 255, 255));
        passwordLbl.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        passwordLbl.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 49;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 120, 0, 0);
        jPanel1.add(passwordLbl, gridBagConstraints);

        passwordTF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 28;
        gridBagConstraints.ipadx = 306;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 20, 0, 0);
        jPanel1.add(passwordTF, gridBagConstraints);

        ageConfirm.setAlignment(java.awt.Label.CENTER);
        ageConfirm.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        ageConfirm.setText(" I confirm +18");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 120, 0, 0);
        jPanel1.add(ageConfirm, gridBagConstraints);

        ageConfirmCB.setBackground(new java.awt.Color(51, 102, 255));
        ageConfirmCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageConfirmCBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 20, 0, 0);
        jPanel1.add(ageConfirmCB, gridBagConstraints);

        mainPageText.setBackground(new java.awt.Color(255, 255, 255));
        mainPageText.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        mainPageText.setForeground(new java.awt.Color(255, 255, 255));
        mainPageText.setText("Account User Profile Form");
        mainPageText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 3, true));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 29;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = -6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 120, 0, 0);
        jPanel1.add(mainPageText, gridBagConstraints);

        mainPageRightImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_chat/User_profile_Front_Back_1.png"))); // NOI18N
        mainPageRightImage.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 43;
        gridBagConstraints.gridheight = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 0);
        jPanel1.add(mainPageRightImage, gridBagConstraints);

        mainPageLeftImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_chat/User_profile_Front_Back_1.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 6;
        gridBagConstraints.ipadx = -6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 0, 0);
        jPanel1.add(mainPageLeftImage, gridBagConstraints);

        MainPageBackgroundImage.setForeground(new java.awt.Color(255, 153, 0));
        MainPageBackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_chat/Form_BackGround.png3.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 46;
        gridBagConstraints.gridheight = 15;
        gridBagConstraints.ipadx = -40;
        gridBagConstraints.ipady = -132;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(MainPageBackgroundImage, gridBagConstraints);
        MainPageBackgroundImage.getAccessibleContext().setAccessibleDescription("");

        mainPageText2.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        mainPageText2.setForeground(new java.awt.Color(102, 0, 102));
        mainPageText2.setText("Account User Profile Form");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = -10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 110, 0, 0);
        jPanel1.add(mainPageText2, gridBagConstraints);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainPageBtnActionPerformed
    // TODO add your handling code here:
      //  fp.setVisible(true);
       // this.setVisible(false);
        
    }//GEN-LAST:event_mainPageBtnActionPerformed

    private void CreateNewUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateNewUserBtnActionPerformed
        // TODO add your handling code here:
       if (ageConfirmCB.isSelected()) {
        // If selected, the user is confirming they are 18 or older
       JOptionPane.showMessageDialog(null, "Profile Created");
       System.out.println("Age confirmed: 18 or older");
       String user = userTF.getText();
       String password = passwordTF.getText();
       String email = emailTF.getText();
       dbc.insertUser(user,password,email);
       
       frontMainPage fmp = new frontMainPage();
       fmp.setVisible(true);
        this.setVisible(false);
        }else{
        // If checkBox is not selected,it means at user is not confirming at his are 18 it not let create Form
        JOptionPane.showMessageDialog(null, "Please confirm that you are 18 or older before creating an account.");
        System.out.println("Please confirm that you are 18 or older before creating an account.");
   
    }
        
        
                
        
        
        
    }//GEN-LAST:event_CreateNewUserBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
     System.exit(WIDTH);
        // TODO add your handling code here:
    }//GEN-LAST:event_exitBtnActionPerformed

    private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed
        // TODO add your handling code here:
        FrameForPanels ffp = new FrameForPanels();
        ffp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_returnBtnActionPerformed

    private void userTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTFActionPerformed

    private void ageConfirmCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageConfirmCBActionPerformed
      // Check if the checkbox is selected

    }//GEN-LAST:event_ageConfirmCBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userProfileForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userProfileForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userProfileForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userProfileForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userProfileForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateNewUserBtn;
    private javax.swing.JLabel MainPageBackgroundImage;
    private java.awt.Label ageConfirm;
    private javax.swing.JCheckBox ageConfirmCB;
    private javax.swing.JTextField emailTF;
    private javax.swing.JButton exitBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private java.awt.Label label4;
    private javax.swing.JButton mainPageBtn;
    private javax.swing.JLabel mainPageLeftImage;
    private javax.swing.JLabel mainPageRightImage;
    private javax.swing.JLabel mainPageText;
    private javax.swing.JLabel mainPageText1;
    private javax.swing.JLabel mainPageText2;
    private java.awt.Label passwordLbl;
    private javax.swing.JTextField passwordTF;
    private javax.swing.JButton returnBtn;
    private java.awt.Label userNameLbl;
    private javax.swing.JTextField userTF;
    // End of variables declaration//GEN-END:variables

    private void insertUser(String user, String password, String email) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
